apiVersion: batch/v1
kind: CronJob
metadata:
  name: email
spec:
  suspend: false
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: email
            image: curlimages/curl:7.72.0
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -ec
            - curl 'http://appjava-service-clusterip:8080/email'
          restartPolicy: Never